version: "2.2"

services:
  redis:
    image: redis
    container_name: redis
    networks:
      - app-net
    ports:
      - "6379:6379"

  postgresql:
    image: postgresql
    container_name: postgresql
    networks:
      - app-net
    ports:
      - "5432:5432"
    environment:
      # create the database with other way
      POSTGRES_USER=dev
      POSTGRES_PASSWORD=123
    volumes:
      - app-storage:/var/lib/postgresql/data

volumes:
  app-storage:
    external: true

networks:
  app-net:
    driver: bridge

