version: "2.2"

services:
  redis:
    image: redis
    container_name: redis
    networks:
      - app-net
    ports:
      - "6379:6379"

  postgresql:
    image: postgresql
    container_name: postgresql
    networks:
      - app-net
    ports:
      - "5432:5432"
    environment:

networks:
  app-net:
    driver: bridge

