server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/priview
    username: dev
    password: 123
    hikari:
      connectionTimeout: 1000
      maximumPoolSize: 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
