server:
  port: 8080

spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATA_BASE_URL:jdbc:postgresql://localhost:5433/petshop-ms-auth}
    username: ${DATA_BASE_USER:dev}
    password: ${DATA_BASE_PASS:123}
#    hikari:
#      connectionTimeout: 10000
#      maximumPoolSize: 1
  jpa:
    open-in-view=false: false
    show-sql: true
    hibernate:
      ddl-auto: validate

security:
  jwt:
    secret: AN_EXTREMALY_DIFFICULT_STRING_TO_BROKEN_FOR_A_NOT_OCCUPIED_PERSON
