server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/petshop-ms-auth
    username: dev
    password: 123
    hikari:
      connectionTimeout: 1000
      maximumPoolSize: 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

security:
  jwt:
    key: AN_EXTREMALY_DIFFICULT_STRING_TO_UNDERSTAND
