server:
  port: 8080

spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/petshop-ms-auth
    username: dev
    password: 123
#    hikari:
#      connectionTimeout: 10000
#      maximumPoolSize: 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

security:
  user:
    password: 123
  jwt:
    key: AN_EXTREMALY_DIFFICULT_STRING_TO_UNDERSTAND
